sudo: false
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - libcppunit-dev
      env:
        - COMPILER='g++-4.9'
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - libcppunit-dev
      env:
        - COMPILER='g++-5'
    - os: osx
      osx_image: xcode8
      env:
        - COMPILER='clang++'

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cppunit; fi
  - export CMAKE=cmake  
  - export CXX=$COMPILER
  - $CMAKE --version
  - $CXX --version
script:
  - mkdir $CXX && cd $CXX
  - $CMAKE -DCMAKE_CXX_COMPILER=$CXX -DCLASP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wall -Wextra" ../
  - make -j3 && make "test"
  - $CMAKE -DCMAKE_CXX_COMPILER=$CXX -DCLASP_BUILD_TESTS=ON -DCLASP_BUILD_WITH_THREADS=OFF -DCMAKE_CXX_FLAGS="-Wall -Wextra" ../
  - make -j3 && make "test"
  
